<?php
/**
 * Created by PhpStorm.
 * User: olha
 * Date: 22.02.16
 * Time: 11:18
 */
?>

<tr>
<td width = "29" style="padding: 0; margin: 0;"></td>
<td colspan = "3"  height="36" style="padding: 0; margin: 0;">
    <table border="0" cellpadding="0" cellspacing="0" width="512" style="border-collapse: collapse;
     mso-table-lspace: 0pt; mso-table-rspace: 0pt; margin-left: auto; margin-right: auto;">
        <tr>
            <td colspan = "2" width = "125" height="12" valign="top" style="padding: 0; margin: 0;"></td>
            <td rowspan = "2" width = "262" height="25" style="padding: 0; margin: 0;
             font-family: 'HelveticaNeue UltraLight', sans-serif; font-size: 24px; text-align: center;
              vertical-align: middle;"> Hello, <span><?= $nameCustomer?></span> </td>
            <td colspan = "2" width = "125" height="12" valign="top" style="padding: 0; margin: 0;"></td>
        </tr>
        <tr>
            <td colspan = "2" width = "125" height="0" valign="top" style="padding: 6px 0; margin: 0; border-top: solid 1px #a3d8f0;"></td>
            <td colspan = "2" width = "125" height="0" valign="top" style="padding: 6px 0; margin: 0; border-top: solid 1px #a3d8f0;"></td>
        </tr>
    </table>
</td>

    <td width = "29" style="padding: 0; margin: 0;"></td>
</tr>
<tr>
    <td width = "29" style="padding: 0; margin: 0;"></td>
    <td colspan = "3"  height="16" style="padding: 19px 0 10px 0; margin: 0; font-family: 'HelveticaNeue Regular',
    sans-serif; font-size: 16px; font-weight: normal; text-align: center;">Your invoice #
    <strong style=" font-family: 'HelveticaNeue Bold', sans-serif; font-size: 16px; font-weight: bold;"><?= $id?></strong></td>
    <td width = "29" style="padding: 0; margin: 0;"></td>
</tr>
<tr>
    <td width = "29" style="padding: 0; margin: 0;"></td>
    <td colspan = "3"  height="15" style="padding: 10px 0 4px 0; margin: 0;
     font-family: 'HelveticaNeue Regular', sans-serif; font-size: 15px;
     font-weight: normal; text-align: center;">This invoice has been generated by Skynix company for the period from:</td>
    <td width = "29" style="padding: 0; margin: 0;"></td>
</tr>
<tr>
    <td width = "29" style="padding: 0; margin: 0;"></td>
    <td colspan = "3"  height="15" style="padding: 0 0 4px 0; margin: 0;
     font-family: 'HelveticaNeue Regular', sans-serif; font-size: 15px;
     font-weight: normal; text-align: center;"><strong style=" font-family: 'HelveticaNeue Bold', sans-serif;
     font-size: 16px; font-weight: bold;"><?= $dataFrom?>  to <?=$dataTo?></strong>
    </td>
    <td width = "29" style="padding: 0; margin: 0;"></td>
</tr>
<tr>
    <td width = "29" style="padding: 0; margin: 0;"></td>
    <td colspan = "3"  height="15" style="padding: 10px 0 28px 0; margin: 0; font-family: 'HelveticaNeue Regular', sans-serif;
    font-size: 15px; font-weight: normal; text-align: center;">The PDF invoice with payment details is attached</td>
    <td width = "29" style="padding: 0; margin: 0;"></td>
</tr>
<tr>
    <td colspan = "5"  height="35" style="padding: 8px 0 5px 0; margin: 0; background-color: #a3d8f0;
        font-family: 'HelveticaNeue Regular', sans-serif; font-size: 15px; text-align: center; color: #fffefe;">
        THANK YOU FOR YOUR COLLABORATION WE APPRECIATE YOUR BUSINESS </td>
</tr>

<tr>
    <td colspan = "5"  height="13" style="padding: 0; margin: 0; background-color: #a3d8f0;"></td>
</tr>