<?php
/**
 * Created by Skynix Team
 * Date: 25.07.17
 * Time: 13:48
 */

namespace viewModel;

use Yii;
use app\modules\api\components\SortHelper;
use app\components\DataTable;
use app\components\DateUtil;
use app\models\FinancialReport;
use yii\helpers\ArrayHelper;
use app\models\User;
use app\modules\api\components\Api\Processor;

/**
 * Class FinancialReportFetch
 * @see     https://jira-v2.skynix.company/browse/SI-1024
 * @package viewModel
 */
class FinancialReportFetch extends ViewModelAbstract
{
    public function define()
    {
        if (User::hasPermission([User::ROLE_ADMIN, User::ROLE_FIN])) {
            $order    = Yii::$app->request->getQueryParam('order');
            $start    = Yii::$app->request->getQueryParam('start') ?: 0;
            $limit    = Yii::$app->request->getQueryParam('limit') ?: SortHelper::DEFAULT_LIMIT;
            $date_raw = Yii::$app->request->getQueryParam('search_query');

            if (!empty($date_raw)){

                $dates = explode("~", $date_raw);

                if ( count($dates) === 2) {

                    $query = FinancialReport::find()
                        ->where(['between', 'report_date',
                            DateUtil::toUnixFromSlashFormat(trim($dates[0])), DateUtil::getLastDayOfMonth(trim($dates[1]))
                        ]);


                }

            } else {
                $query = FinancialReport::find();
            }

            $dataTable = DataTable::getInstance()
                ->setQuery($query)
                ->setLimit($limit)
                ->setStart($start);

            if ($order) {
                foreach ($order as $name => $value) {
                    $dataTable->setOrder(FinancialReport::tableName() . '.' . $name, $value);
                }

            } else {
                $dataTable->setOrder(FinancialReport::tableName() . '.id', 'desc');
            }

            $financialReport = $dataTable->getData();

            if ($financialReport) {

                foreach ($financialReport as $key => $finRep) {
                    $financialReport[$key] = [
                        'id'                  => $finRep->id,
                        'report_date'         => DateUtil::dateRangeForFetch($finRep->report_date),
                        'balance'             => strval(FinancialReport::getBalance($finRep->id)),
                        'currency'            => $finRep->currency ? $finRep->currency : 0,
                        'expenses'            => strval(FinancialReport::sumExpenses($finRep->id)),
                        'investments'         => strval(FinancialReport::sumInvestments($finRep->id)),
                        'spent_corp_events'   => strval(FinancialReport::sumSpentCorpEvents($finRep->id)),
                        'num_of_working_days' => $finRep->num_of_working_days,
                        'is_locked'           => $finRep->is_locked
                    ];
                    if (User::hasPermission([User::ROLE_ADMIN])) {
                        $financialReport[$key]['income'] = FinancialReport::sumIncome($finRep->id);
                        $financialReport[$key]['profit'] = FinancialReport::getProfit($finRep->id);
                    }
                }

            } else {
                $financialReport = [];
            }

            $this->setData($financialReport);

        } else {
            return $this->addError(Processor::ERROR_PARAM, Yii::t('yii', 'You have no permission for this action'));
        }

    }

    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
        Yii::$app->response->content = json_encode([
            'financialReport' => $this->data,
            'meta' => [
                'total' => DataTable::getInstance()->getTotal(),
                'errors' => $this->errors,
                'success' => count($this->errors) == 0 ? true : false
            ]
        ]);
    }

}

