<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\models\User;
use app\models\ProjectCustomer;
use app\components\DateUtil;

/**
 * This is the model class for table "invoices".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $note
 * @property string $subtotal
 * @property string $discount
 * @property string $total
 * @property string $date_start
 * @property string $date_end
 * @property string $date_created
 * @property string $date_paid
 * @property string $date_sent
 * @property string $status
 * @property string $total_hours
 * @property integer $contract_number
 * @property integer $act_of_work

 *
 * @property Report[] $reports
 */
class Invoice extends \yii\db\ActiveRecord
{
    const STATUS_NEW        = "NEW";
    const STATUS_CANCELED   = "CANCELED";
    const STATUS_PAID       = "PAID";

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoices';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [['id', 'user_id', 'contract_number', 'act_of_work'], 'integer'],
            [['subtotal', 'discount', 'total', 'total_hours'], 'number'],
            [['date_start', 'date_end', 'date_created', 'date_paid', 'date_sent'], 'safe'],
            [['status', 'note'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'note' => 'Notes',
            'subtotal' => 'Subtotal',
            'discount' => 'Discount',
            'total' => 'Total',
            'date_start' => 'Date Start',
            'date_end' => 'Date End',
            'date_created' => 'Date Created',
            'date_paid' => 'Date Paid',
            'date_sent' => 'Date Sent',
            'status' => 'Status',
            'total_hours' => 'Total Hours',
            'contract_number' => 'Contract Number',
            'act_of_work' => 'Act of Work',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReports()
    {
        return $this->hasMany(Report::className(), ['invoice_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if( $this->isNewRecord ) {

            $this->date_start = DateUtil::convertData($this->date_start);

            $this->date_end = DateUtil::convertData($this->date_end);

            $this->status = Invoice::STATUS_NEW;

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $projectsCustomer = ProjectCustomer::getReportsOfCustomer($this->user_id);
        $projectId = [];
        foreach($projectsCustomer as $project){

            $projectId[] = $project->project_id;

        }

        $connection = Yii::$app->db;

        $connection->createCommand()
            ->update(Report::tableName(), [

                'invoice_id' => $this->id,
                'status' => Report::STATUS_INVOICED,

            ], 'project_id IN ('. implode(', ', $projectId) .') AND date_report BETWEEN :start AND :end AND is_delete=0',
                [
                ':start'    => DateUtil::convertData($this->date_start),
                ':end'      => DateUtil::convertData($this->date_end),
                ])
            ->execute();


        $sum = (new \yii\db\Query())->from('reports')->where('invoice_id='. $this->id)->sum('hours');

        $connection->createCommand()
            ->update(Invoice::tableName(), [

                'total_hours' => $sum,

            ], 'id=:Id',
                [
                    ':Id'    => $this->id,
                ])
            ->execute();

       /* $connection->createCommand("SELECT SUM(hours) FROM report WHERE id=:Id")
                                    ->bindValue(':Id', $this->id)
                                    ->queryScalar();*/

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
