<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "teams".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property string $date_created
 * @property integer $is_deleted
 * @property integer $team_leader_id
 *
 * @property User $user
 */
class Team extends \yii\db\ActiveRecord
{
    public $teammate;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'teams';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'name', 'team_leader_id'], 'required'],
            [['user_id', 'is_deleted', 'team_leader_id'], 'integer'],
            [['date_created'], 'safe'],
            [['name'], 'string', 'max' => 150]
        ];


    }
    /**
     * @inheritdoc
     */
    /*public static function isUserHasPermission($userId)
    {
        return self::find()->andWhere(['user_id'=>$userId])->count();

    }*/
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'name' => 'Name',
            'date_created' => 'Date Created',
            'is_deleted' => 'Is Deleted',
            'team_leader_id' => 'Team Leader'
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getLeader()
    {
        return $this->hasOne(User::className(), ['id' => 'team_leader_id']);
    }

   /* public static function hasTeam($currentUserId)
    {
        $users_id = Team::find()
            ->leftJoin(Teammate::tableName(), Teammate::tableName() . '.team_id=id')
            ->where(Team::tableName() . '.is_deleted=0')
            ->all();*/

    /**
     *
     * @param $currentUserId
     */
    public static function hasTeam($currentUserId)
    {
        /**
         *         SELECT COUNT(*) FROM teammates tm
         *           LEFT JOIN teams t ON tm.team_id=t.id
         *           WHERE t.is_deleted=0 AND tm.is_deleted=0 AND tm.user_id=10;
         */


        $c = Teammate::find()
                ->leftJoin(Team::tableName(), Teammate::tableName() . '.team_id=' . Team::tableName() . '.id' )
                ->where( Team::tableName() . '.is_deleted=0 AND ' .
                        Teammate::tableName() . '.is_deleted=0 AND ' .
                        Teammate::tableName() . '.user_id=:uid', [':uid' => $currentUserId])
                ->count();
        return ( $c > 0 ? true : false);

    }

    public function afterSave($insert, $changedAttributes)
    {
        $modelTeammate = new Teammate();
        $modelTeammate->team_id = $this->id;
        $modelTeammate->user_id = $this->team_leader_id;

        if ($modelTeammate->validate()) {

            $modelTeammate->save();

        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
